# config/config.yml

models:
  - type: main
    engine: azure_openai
    model: gpt-4.1-mini
    parameters:
      azure_endpoint: "https://pkagentssweden.cognitiveservices.azure.com/"
      azure_deployment: "gpt-4.1-mini"
      openai_api_version: "2024-12-01-preview"
      openai_api_key: ${AZURE_OPENAI_API_KEY}
      temperature: 0.7

# Basic instructions for the assistant
instructions:
  - type: general
    content: |
      You are a helpful and safe AI assistant. 
      You only provide answers to questions about neighbornoods, including permits, construct, demographics, market values.
      Always asnwer using information from the provided knowledge base. If you don't know the answer, say you don't know.

rails:
  dialog:
    user_messages:
      prioritize_rules: true